exclude: "^\
  (gradlew)\
  "
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.24.0
    hooks:
      - id: commitlint
        verbose: false
        name: Commit message format
        stages:
          - commit-msg
        additional_dependencies: ["@open-turo/commitlint-config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        name: Format files with prettier
        exclude: docker
        stages:
          - commit
        language_version: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: detekt
        name: Run Detekt
        entry: ./gradlew detekt --continue
        language: system
        files: \.kt$
        pass_filenames: false
